import { NextResponse } from "next/server";
import { getSessionUser } from "@/lib/auth";
import { prisma } from "@/lib/db";
import { uploadToShelby } from "@/lib/shelby-server";
import { getShelbyPublicUrl } from "@/lib/shelby";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ id: string }> }
) {
  const user = await getSessionUser();
  if (!user) return NextResponse.json({ error: "Unauthorized" }, { status: 401 });

  const { id } = await params;
  const invoice = await prisma.invoice.findFirst({
    where: { id, issuerId: user.id },
    include: { issuer: { select: { displayName: true, username: true } } },
  });

  if (!invoice) return NextResponse.json({ error: "Not found" }, { status: 404 });

  if (invoice.pdfBlobId) {
    return NextResponse.redirect(getShelbyPublicUrl(invoice.pdfBlobId));
  }

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Invoice ${invoice.invoiceNumber}</title>
<style>
  body { font-family: system-ui, sans-serif; color: #313131; padding: 40px; max-width: 720px; margin: 0 auto; background: #f5f5f5; }
  .card { background: #eee; padding: 32px; border-radius: 8px; }
  h1 { color: #dc5429; margin: 0; }
  table { width: 100%; border-collapse: collapse; margin-top: 24px; }
  td, th { border: 1px solid #bdbdbd; padding: 10px; text-align: left; }
  .meta { color: #5a5a5a; font-size: 14px; }
</style></head><body>
<div class="card">
  <h1>Forge</h1>
  <p class="meta">Invoice ${invoice.invoiceNumber}</p>
  <p><strong>From:</strong> ${invoice.issuer.displayName || invoice.issuer.username || "Creator"}</p>
  <p><strong>To:</strong> ${invoice.clientName}${invoice.clientEmail ? ` (${invoice.clientEmail})` : ""}</p>
  <p><strong>Date:</strong> ${invoice.createdAt.toLocaleDateString()}</p>
  <p><strong>Status:</strong> ${invoice.status}</p>
  <table>
    <tr><th>Description</th><th>Amount</th></tr>
    <tr><td>${invoice.description}</td><td>${invoice.amountApt} ${invoice.currency}</td></tr>
  </table>
  ${invoice.notes ? `<p><strong>Notes:</strong> ${invoice.notes}</p>` : ""}
  <p class="meta" style="margin-top:32px">Generated by Forge · Aptos · Shelby</p>
</div>
</body></html>`;

  try {
    const upload = await uploadToShelby(
      new Blob([html], { type: "text/html" }),
      `${invoice.invoiceNumber}.html`,
      { type: "invoice" }
    );
    await prisma.invoice.update({
      where: { id: invoice.id },
      data: { pdfBlobId: upload.cid },
    });
    return NextResponse.redirect(getShelbyPublicUrl(upload.cid));
  } catch {
    // Return inline HTML if Shelby upload unavailable
  }

  return new NextResponse(html, {
    headers: {
      "Content-Type": "text/html",
      "Content-Disposition": `attachment; filename="${invoice.invoiceNumber}.html"`,
    },
  });
}
